//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopinformation
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Adress { get; set; }
        public string Shopphone { get; set; }
        public int Capital { get; set; }
        public string Profile { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        public virtual Owner_s Owner_s { get; set; }
    }
}
