USE [master]
GO

/****** Object:  Database [SettShop]    Script Date: 17.05.2021 17:31:13 ******/
CREATE DATABASE [SettShop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SettShop', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SettShop.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SettShop_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SettShop_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SettShop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SettShop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SettShop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SettShop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SettShop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SettShop] SET ARITHABORT OFF 
GO

ALTER DATABASE [SettShop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SettShop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SettShop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SettShop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SettShop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SettShop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SettShop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SettShop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SettShop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SettShop] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SettShop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SettShop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SettShop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SettShop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SettShop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SettShop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SettShop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SettShop] SET RECOVERY FULL 
GO

ALTER DATABASE [SettShop] SET  MULTI_USER 
GO

ALTER DATABASE [SettShop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SettShop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SettShop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SettShop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SettShop] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SettShop] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SettShop] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SettShop] SET  READ_WRITE 
GO

